# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
alias GigalixirGettingStarted.{Repo, Song}

Repo.insert!(%Song{name: "9 to 5 jam", author: "Dolly Parton"})
Repo.insert!(%Song{name: "9 x 9 jam", author: "Benevento/Russo Duo"})
Repo.insert!(%Song{name: "A Hard Rain's A-Gonna Fall", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Aiko Aiko", author: "(trad)"})
Repo.insert!(%Song{name: "Alabama Getaway"})
Repo.insert!(%Song{name: "Alice D. Millionaire"})
Repo.insert!(%Song{name: "All Along The Watchtower", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Alligator"})
Repo.insert!(%Song{name: "All New Minglewood Blues"})
Repo.insert!(%Song{name: "Althea"})
Repo.insert!(%Song{name: "Althea reprise"})
Repo.insert!(%Song{name: "At A Siding theme"})
Repo.insert!(%Song{name: "Atlantic City", author: "Bruce Springsteen"})
Repo.insert!(%Song{name: "Auld Lang Syne", author: "(trad)"})
Repo.insert!(%Song{name: "Bass jam"})
Repo.insert!(%Song{name: "Bass solo"})
Repo.insert!(%Song{name: "Beat It On Down The Line"})
Repo.insert!(%Song{name: "Becky", author: "Benevento/Russo Duo"})
Repo.insert!(%Song{name: "Been Caught Stealing", author: "Jane's Addiction"})
Repo.insert!(%Song{name: "Bertha"})
Repo.insert!(%Song{name: "Big Railroad Blues"})
Repo.insert!(%Song{name: "Big River"})
Repo.insert!(%Song{name: "Big Whopper", author: "Benevento/Russo Duo"})
Repo.insert!(%Song{name: "Bird Song"})
Repo.insert!(%Song{name: "Bird Song jam"})
Repo.insert!(%Song{name: "Bird Song reprise"})
Repo.insert!(%Song{name: "Black Peter"})
Repo.insert!(%Song{name: "Black Throated Wind"})
Repo.insert!(%Song{name: "Black Throated Wind jam"})
Repo.insert!(%Song{name: "Black Throated Wind reprise"})
Repo.insert!(%Song{name: "Blues For Allah (instrumental)"})
Repo.insert!(%Song{name: "Blues jam"})
Repo.insert!(%Song{name: "Born Cross Eyed"})
Repo.insert!(%Song{name: "Born Cross Eyed jam"})
Repo.insert!(%Song{name: "Born Cross Eyed jam reprise"})
Repo.insert!(%Song{name: "Born To Run", author: "Bruce Springsteen"})
Repo.insert!(%Song{name: "Box Of Rain"})
Repo.insert!(%Song{name: "Brokedown Palace"})
Repo.insert!(%Song{name: "Brown-Eyed Women"})
Repo.insert!(%Song{name: "Brown-Eyed Women reprise"})
Repo.insert!(%Song{name: "Bubblehouse", author: "Medeski Martin and Wood"})
Repo.insert!(%Song{name: "Built To Last"})
Repo.insert!(%Song{name: "Candyman"})
Repo.insert!(%Song{name: "Can't Turn You Loose jam"})
Repo.insert!(%Song{name: "Casey Jones"})
Repo.insert!(%Song{name: "Cassidy"})
Repo.insert!(%Song{name: "Cassidy jam"})
Repo.insert!(%Song{name: "Caution (Do Not Stop On Tracks) jam"})
Repo.insert!(%Song{name: "China Cat Sunflower"})
Repo.insert!(%Song{name: "China Cat Sunflower jam"})
Repo.insert!(%Song{name: "China Cat Sunflower reprise"})
Repo.insert!(%Song{name: "Chuckles", author: "WOLF!"})
Repo.insert!(%Song{name: "Chuckles reprise", author: "WOLF!"})
Repo.insert!(%Song{name: "Cinnamon & Lesbians", author: "Stephen Malkmus"})
Repo.insert!(%Song{name: "Cold Rain and Snow"})
Repo.insert!(%Song{name: "Cold Rain and Snow jam"})
Repo.insert!(%Song{name: "Cosmic Charlie jam"})
Repo.insert!(%Song{name: "Crazy Fingers jam"})
Repo.insert!(%Song{name: "Crazy Fingers"})
Repo.insert!(%Song{name: "Cream Puff War"})
Repo.insert!(%Song{name: "Cryptical Envelopment"})
Repo.insert!(%Song{name: "Cryptical Envelopment jam"})
Repo.insert!(%Song{name: "Cryptical Envelopment reprise"})
Repo.insert!(%Song{name: "Cumberland Blues"})
Repo.insert!(%Song{name: "Cumberland Blues reprise"})
Repo.insert!(%Song{name: "Dance Of The Sugar Plum Fairy", author: "Tchaikovsky"})
Repo.insert!(%Song{name: "Dancing In The Streets"})
Repo.insert!(%Song{name: "Dancing In The Streets jam"})
Repo.insert!(%Song{name: "Dancing In The Streets reprise"})
Repo.insert!(%Song{name: "Dark Hollow"})
Repo.insert!(%Song{name: "Dark Star jam"})
Repo.insert!(%Song{name: "Dark Star verse 1"})
Repo.insert!(%Song{name: "Dark Star verse 2"})
Repo.insert!(%Song{name: "Dark Star"})
Repo.insert!(%Song{name: "Day Tripper"})
Repo.insert!(%Song{name: "Deal"})
Repo.insert!(%Song{name: "Deep Elem Blues"})
Repo.insert!(%Song{name: "Dire Wolf"})
Repo.insert!(%Song{name: "Doin' That Rag"})
Repo.insert!(%Song{name: "Don't Do It", author: "Holland-Dozier-Holland"})
Repo.insert!(%Song{name: "Don't Ease Me In"})
Repo.insert!(%Song{name: "Drums"})
Repo.insert!(%Song{name: "Duo jam", author: "Benevento/Russo Duo"})
Repo.insert!(%Song{name: "Dupree's Diamond Blues"})
Repo.insert!(%Song{name: "Easy Wind"})
Repo.insert!(%Song{name: "Elizabeth Reed jam", author: "Allmans"})
Repo.insert!(%Song{name: "Estimated Prophet"})
Repo.insert!(%Song{name: "Estimated Prophet jam"})
Repo.insert!(%Song{name: "Eyes Of The World"})
Repo.insert!(%Song{name: "Fame", author: "David Bowie"})
Repo.insert!(%Song{name: "Fame jam", author: "David Bowie"})
Repo.insert!(%Song{name: "Feel Like A Stranger"})
Repo.insert!(%Song{name: "Fifty Ways to Leave Your Lover jam", author: "Paul Simon"})
Repo.insert!(%Song{name: "Fire On The Mountain"})
Repo.insert!(%Song{name: "Fortune Teller", author: "Allen Toussanit"})
Repo.insert!(%Song{name: "Franklin's Tower"})
Repo.insert!(%Song{name: "Franklin's Tower reprise"})
Repo.insert!(%Song{name: "Friend Of The Devil"})
Repo.insert!(%Song{name: "Friends jam", author: "Led Zepplin"})
Repo.insert!(%Song{name: "Girlfriend Is Better jam", author: "Talking Heads"})
Repo.insert!(%Song{name: "God Put A Smile Upon Your Face jam", author: "Cold Play"})
Repo.insert!(%Song{name: "Going Down The Road Feeling Bad"})
Repo.insert!(%Song{name: "Going Down The Road Feeling Bad jam"})
Repo.insert!(%Song{name: "Golden Road (To Unlimited Devotion)"})
Repo.insert!(%Song{name: "Gonesville", author: "Bob Weir"})
Repo.insert!(%Song{name: "Good Lovin'"})
Repo.insert!(%Song{name: "Good Lovin' reprise"})
Repo.insert!(%Song{name: "Good Morning Little School Girl", author: "Sonny Boy Williamson"})
Repo.insert!(%Song{name: "Greatest Story Ever Told"})
Repo.insert!(%Song{name: "Greatest Story Ever Told reprise"})
Repo.insert!(%Song{name: "\"Halloween\" Theme Main Title", author: "John Carpenter"})
Repo.insert!(%Song{name: "Happy Birthday", author: "(trad)"})
Repo.insert!(%Song{name: "Hard To Handle", author: "Otis Redding"})
Repo.insert!(%Song{name: "Harry Hood jam", author: "Phish"})
Repo.insert!(%Song{name: "He's Gone"})
Repo.insert!(%Song{name: "He Was a Friend of Mine", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Heartbreaker jam"})
Repo.insert!(%Song{name: "Hell In A Bucket"})
Repo.insert!(%Song{name: "Hell in A Bucket jam"})
Repo.insert!(%Song{name: "Help On The Way"})
Repo.insert!(%Song{name: "Here Comes Sunshine"})
Repo.insert!(%Song{name: "Here Comes Sunshine jam"})
Repo.insert!(%Song{name: "Here Comes Sunshine reprise"})
Repo.insert!(%Song{name: "Hey Bo Diddley jam", author: "Bo Diddley"})
Repo.insert!(%Song{name: "Hey Bulldog", author: "The Beatles"})
Repo.insert!(%Song{name: "Hippy Dream", author: "Neil Young"})
Repo.insert!(%Song{name: "Hoo Doo Voo Doo", author: "Wilco/B Bragg/W. Guthrie"})
Repo.insert!(%Song{name: "I Am The Walrus", author: "The Beatles"})
Repo.insert!(%Song{name: "Iko Iko jam"})
Repo.insert!(%Song{name: "I Know You Rider"})
Repo.insert!(%Song{name: "I'm Writing A Novel", author: "Father John Misty"})
Repo.insert!(%Song{name: "I Need A Miracle"})
Repo.insert!(%Song{name: "In Memory of Elizabeth Reed", author: "Allman Brothers Band"})
Repo.insert!(%Song{name: "In Memory of Elizabeth Reed jam", author: "Allman Brothers Band"})
Repo.insert!(%Song{name: "\"In With The In Crowd\" jam", author: "Ramsey Lewis"})
Repo.insert!(%Song{name: "It's All Over Now Baby Blue", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Jack A Roe"})
Repo.insert!(%Song{name: "Jack Straw"})
Repo.insert!(%Song{name: "Jack Straw jam"})
Repo.insert!(%Song{name: "Jam"})
Repo.insert!(%Song{name: "Joeline", author: "Tom Hamilton"})
Repo.insert!(%Song{name: "Kashmir", author: "Led Zeppelin"})
Repo.insert!(%Song{name: "Keeping It Simple", author: "JRAD"})
Repo.insert!(%Song{name: "Killer Cars", author: "Radiohead"})
Repo.insert!(%Song{name: "King Bee", author: "Slim Harpo"})
Repo.insert!(%Song{name: "King Bee jam", author: "Slim Harpo"})
Repo.insert!(%Song{name: "King Solomon's Marbles"})
Repo.insert!(%Song{name: "King Solomon's Marbles reprise"})
Repo.insert!(%Song{name: "LA Woman jam", author: "The Doors"})
Repo.insert!(%Song{name: "Lazy Lightning"})
Repo.insert!(%Song{name: "Lazy Lightning reprise"})
Repo.insert!(%Song{name: "Lemon Song", author: "Led Zeppelin / Robert Johnson"})
Repo.insert!(%Song{name: "Life Is A Carnival", author: "The Band"})
Repo.insert!(%Song{name: "Little Red Rooster", author: "Willie Dixon"})
Repo.insert!(%Song{name: "Lonesome Whistle Blues", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Looks Like Rain"})
Repo.insert!(%Song{name: "Loose Lucy"})
Repo.insert!(%Song{name: "Loose Lucy reprise"})
Repo.insert!(%Song{name: "Loser"})
Repo.insert!(%Song{name: "Lost Sailor"})
Repo.insert!(%Song{name: "Magnificent Sanctuary Band", author: "Jerry Garcia Band"})
Repo.insert!(%Song{name: "Mama Tried"})
Repo.insert!(%Song{name: "Mason's Children"})
Repo.insert!(%Song{name: "Me And My Uncle"})
Repo.insert!(%Song{name: "Mission In The Rain"})
Repo.insert!(%Song{name: "Mississippi Halfstep Uptown Toodeloo"})
Repo.insert!(%Song{name: "Mississippi Halfstep Uptown Toodeloo jam"})
Repo.insert!(%Song{name: "Moby Dick", author: "Led Zeppelin"})
Repo.insert!(%Song{name: "Morfbeats"})
Repo.insert!(%Song{name: "Morning Dew"})
Repo.insert!(%Song{name: "Mountains Of The Moon"})
Repo.insert!(%Song{name: "Mr. Charlie"})
Repo.insert!(%Song{name: "Must Have Been The Roses"})
Repo.insert!(%Song{name: "My Brother Esau"})
Repo.insert!(%Song{name: "My Sharona jam", author: "The Knack"})
Repo.insert!(%Song{name: "Myxomatosis jam", author: "Radiohead"})
Repo.insert!(%Song{name: "National Anthem jam", author: "Radiohead"})
Repo.insert!(%Song{name: "New Orleans March"})
Repo.insert!(%Song{name: "New Speedway Boogie"})
Repo.insert!(%Song{name: "New Speedway Boogie jam"})
Repo.insert!(%Song{name: "New Speedway Boogie reprise"})
Repo.insert!(%Song{name: "No Quarter jam", author: "Led Zeppelin"})
Repo.insert!(%Song{name: "Not Fade Away"})
Repo.insert!(%Song{name: "Not Fade Away jam"})
Repo.insert!(%Song{name: "Not Fade Away reprise"})
Repo.insert!(%Song{name: "One More Saturday Night"})
Repo.insert!(%Song{name: "One More Saturday Night reprise"})
Repo.insert!(%Song{name: "Only Daddy That'll Walk The Line", author: "Waylon Jennings"})
Repo.insert!(%Song{name: "On The Road Again"})
Repo.insert!(%Song{name: "Ophelia", author: "The Band"})
Repo.insert!(%Song{name: "Paranoid Android jam", author: "Radiohead"})
Repo.insert!(%Song{name: "Passenger"})
Repo.insert!(%Song{name: "Piano solo"})
Repo.insert!(%Song{name: "Play, Pause, Stop", author: "Benevento/Russo Duo"})
Repo.insert!(%Song{name: "Playin' In The Band"})
Repo.insert!(%Song{name: "Playin' In The Band reprise"})
Repo.insert!(%Song{name: "Pork & Slaw", author: "WOLF!"})
Repo.insert!(%Song{name: "Pride of Cucamonga"})
Repo.insert!(%Song{name: "Promised Land", author: "Chuck Berry"})
Repo.insert!(%Song{name: "Quinn The Eskimo", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Race Is On"})
Repo.insert!(%Song{name: "Ramble On Rose"})
Repo.insert!(%Song{name: "Reuben & Cherise"})
Repo.insert!(%Song{name: "Revolution No. 9", author: "The Beatles"})
Repo.insert!(%Song{name: "Ripple"})
Repo.insert!(%Song{name: "Row Jimmy"})
Repo.insert!(%Song{name: "Royals jam", author: "Lorde"})
Repo.insert!(%Song{name: "Saint of Circumstance"})
Repo.insert!(%Song{name: "Samson and Delilah"})
Repo.insert!(%Song{name: "Scarlet Begonias"})
Repo.insert!(%Song{name: "Shakedown Street"})
Repo.insert!(%Song{name: "Shakedown Street reprise"})
Repo.insert!(%Song{name: "Shelter From The Storm", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Silvio", author: "Robert Hunter/Bob Dylan"})
Repo.insert!(%Song{name: "Sitting On Top Of The World"})
Repo.insert!(%Song{name: "Slipknot!"})
Repo.insert!(%Song{name: "Slipknot! reprise"})
Repo.insert!(%Song{name: "So Long Jerry", author: "Ween"})
Repo.insert!(%Song{name: "So Many Roads"})
Repo.insert!(%Song{name: "So What jam", author: "Miles Davis"})
Repo.insert!(%Song{name: "Space jam"})
Repo.insert!(%Song{name: "St. Stephen"})
Repo.insert!(%Song{name: "St. Stephen jam"})
Repo.insert!(%Song{name: "St. Stephen reprise"})
Repo.insert!(%Song{name: "Stagger Lee"})
Repo.insert!(%Song{name: "Standing On The Moon"})
Repo.insert!(%Song{name: "Stella Blue"})
Repo.insert!(%Song{name: "Stella Blue jam"})
Repo.insert!(%Song{name: "Such A Night", author: "Dr John"})
Repo.insert!(%Song{name: "Sugar Magnolia"})
Repo.insert!(%Song{name: "Sugaree"})
Repo.insert!(%Song{name: "Summer Nights jam", author: "Jim Jacobs / Warren Casey"})
Repo.insert!(%Song{name: "Sunshine Daydream"})
Repo.insert!(%Song{name: "Superstition jam", author: "Stevie Wonder"})
Repo.insert!(%Song{name: "Supplication jam"})
Repo.insert!(%Song{name: "Tell Me, Momma", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Tennessee Jed"})
Repo.insert!(%Song{name: "Tennessee Jed reprise"})
Repo.insert!(%Song{name: "Tequila", author: "The Champs"})
Repo.insert!(%Song{name: "Terrapin Flyer"})
Repo.insert!(%Song{name: "Terrapin Station jam"})
Repo.insert!(%Song{name: "Terrapin Station part 1"})
Repo.insert!(%Song{name: "Terrapin Station part 2"})
Repo.insert!(%Song{name: "Thank You Sean"})
Repo.insert!(%Song{name: "That's The Way jam", author: "Led Zeppelin"})
Repo.insert!(%Song{name: "The Bends", author: "Radiohead"})
Repo.insert!(%Song{name: "The Eleven"})
Repo.insert!(%Song{name: "The Eleven jam"})
Repo.insert!(%Song{name: "The Music Never Stopped"})
Repo.insert!(%Song{name: "The Music Never Stopped jam"})
Repo.insert!(%Song{name: "The Music Never Stopped reprise"})
Repo.insert!(%Song{name: "The Night They Drove Old Dixie Down", author: "The Band"})
Repo.insert!(%Song{name: "The Other One"})
Repo.insert!(%Song{name: "The Other One jam"})
Repo.insert!(%Song{name: "The Stranger (Two Souls In Communion)"})
Repo.insert!(%Song{name: "The Weight", author: "The Band"})
Repo.insert!(%Song{name: "The Wheel"})
Repo.insert!(%Song{name: "The Wheel jam"})
Repo.insert!(%Song{name: "The Wheel reprise"})
Repo.insert!(%Song{name: "There Is A Mountain", author: "Donovan"})
Repo.insert!(%Song{name: "They Love Each Other"})
Repo.insert!(%Song{name: "Third Stone From The Sun jam"})
Repo.insert!(%Song{name: "Three Question Marks jam", author: "Joe Lukasik"})
Repo.insert!(%Song{name: "Throwing Stones"})
Repo.insert!(%Song{name: "Throwing Stones jam"})
Repo.insert!(%Song{name: "Throwing Stones reprise"})
Repo.insert!(%Song{name: "Tico Tico", author: "Zequinha de Abreu"})
Repo.insert!(%Song{name: "Til The Morning Comes"})
Repo.insert!(%Song{name: "Touch Of Grey"})
Repo.insert!(%Song{name: "Tough Mama", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Truckin'"})
Repo.insert!(%Song{name: "Truckin' reprise"})
Repo.insert!(%Song{name: "Turn On Your Lovelight"})
Repo.insert!(%Song{name: "Tzofeh", author: "Masada"})
Repo.insert!(%Song{name: "U.S. Blues"})
Repo.insert!(%Song{name: "Unbroken Chain"})
Repo.insert!(%Song{name: "Unbroken Chain jam"})
Repo.insert!(%Song{name: "Uncle John's Band"})
Repo.insert!(%Song{name: "Uncle John's Band jam"})
Repo.insert!(%Song{name: "Uncle John's Band reprise"})
Repo.insert!(%Song{name: "Vampire Blues", author: "Neil Young"})
Repo.insert!(%Song{name: "Viola Lee Blues"})
Repo.insert!(%Song{name: "Viola Lee Blues reprise"})
Repo.insert!(%Song{name: "We Bid You Goodnight (instrumental)"})
Repo.insert!(%Song{name: "We Bid You Goodnight"})
Repo.insert!(%Song{name: "Weather Report Suite part 1"})
Repo.insert!(%Song{name: "Weather Report Suite part 2"})
Repo.insert!(%Song{name: "Weather Report Suite part 2 reprise"})
Repo.insert!(%Song{name: "Werevolves of London", author: "Warren Zevon"})
Repo.insert!(%Song{name: "West LA Fadeaway"})
Repo.insert!(%Song{name: "Wharf Rat"})
Repo.insert!(%Song{name: "Wharf Rat jam"})
Repo.insert!(%Song{name: "When I Paint My Masterpiece", author: "Bob Dylan"})
Repo.insert!(%Song{name: "Whole Lotta Love jam", author: "Led Zepplin"})
Repo.insert!(%Song{name: "Women Are Smarter"})
